In [1]:
import numpy as np

In [2]:
matrix1=np.array([[1,2,3],[4,5,6]])

In [8]:
matrix2=np.array([[7,8,9],[3,5,6],[2,1,3]])

In [9]:
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [10]:
print(matrix2)

[[7 8 9]
 [3 5 6]
 [2 1 3]]


In [11]:
result=np.dot(matrix1,matrix2)

In [13]:
print(result)

[[19 21 30]
 [55 63 84]]


In [14]:
transpose=np.transpose(result)

In [15]:
print(transpose)

[[19 55]
 [21 63]
 [30 84]]
